#
# Copyright (c) Andras Csizmadia <andras@vpmedia.hu> (www.vpmedia.hu)
# author: Andras Csizmadia <andras@vpmedia.hu>
#

image: node:18

pipelines:
  default:
    - parallel:
        - step:
            name: Install | Build | Test | Lint
            script:
              - npm install
              - npm run build
              - npm run test
              - npm run lint
            caches:
              - node
